server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: C:\code\study\msa-spring-cloud-config  # local git repository path
          uri: https://github.com/sazzeo/mas-config-yml-repo  # remote git repository path
#          username:   private repository 이용시 설정 추가
#          password:

  rabbitmq:  #호스트 정보 기술 => ms는 클라이언트
    host: 127.0.0.1
    port: 5672 # 15672 는 rabbit mq 관리 페이지 접속용
    username: guest
    password: guest


# git이 아닌 로컬 폴더 이용시
#spring:
#  application:
#    name: config-service
#  profiles:
#    active : native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations:  #로컬 폴더명
management:
  endpoints:
    web:
      exposure:
        include: health , busrefresh  #host인 본인도 client 역할을 같이함.
