server:
  port: 8000
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: api-gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://ZUUL-CLIENT-FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters: #필터 추가하기
            #            - AddRequestHeader=first-request , first-request-header2  # key , value  => 필터 클래스 없이 그냥 등록하는 법. 단순 작업만 가능
            #            - AddResponseHeader=first-response , first-response-header2
            - CustomFilter
        - id: first-service
          uri: lb://ZUUL-CLIENT-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            #            - AddRequestHeader=second-request , second-request-header2
            #            - AddResponseHeader=second-response , second-response-header2
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway GlobalFilter
                preLogger: true
                postLogger: true
      default-filters: # 글로벌 필터 지정하기 => 항상 맨 처음에 시작 되어 가장 마지막에 끝남.
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true

