server:
  port: 8761 #유레카 서버를 웹서버로 올릴 때 사용할 포트번호

spring:
  application:
    name: ecommerce #각각 마이크로 서비스마다 부여할 고유 아이디(중복 불가)
  config:
    import: "optional:configserver:"


#유레카 클라이언트 역할 기능 끄기 (기본이 true라 꺼준다)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
