server:
  port: 9001 #클라이언트 포트

spring:
  application:
    name: user-service #각각 마이크로 서비스마다 부여할 고유 아이디(중복 불가)
  config:
    import: "optional:configserver:"


#유레카 클라이언트 역할 기능 켜기
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true #서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지?
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  #유레카 서버의 위치를 등록함